In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences

sent = [  'the glass of milk',
         'the glass of juice',
         'the cup of tea',
         'I am a good boy',
         'I am a good developer',
         'understand the meaning of words',
         'your videos are good',

]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## Define the vocabulary size
voc_size = 10000

## One hot representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr


[[348, 5458, 1422, 1303],
 [348, 5458, 1422, 1494],
 [348, 5742, 1422, 6545],
 [953, 6642, 2405, 1998, 9796],
 [953, 6642, 2405, 1998, 6480],
 [3881, 348, 7388, 1422, 7739],
 [9269, 5411, 7724, 1998]]

In [12]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [17]:
sent_length =  8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  348 5458 1422 1303]
 [   0    0    0    0  348 5458 1422 1494]
 [   0    0    0    0  348 5742 1422 6545]
 [   0    0    0  953 6642 2405 1998 9796]
 [   0    0    0  953 6642 2405 1998 6480]
 [   0    0    0 3881  348 7388 1422 7739]
 [   0    0    0    0 9269 5411 7724 1998]]


In [18]:
## Feature Representation
dim = 10

In [19]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 742ms/step


array([[[-0.00040803,  0.02106554, -0.0353395 ,  0.00684258,
         -0.01241169, -0.04524273,  0.02328255,  0.01999135,
         -0.01833928,  0.02786035],
        [-0.00040803,  0.02106554, -0.0353395 ,  0.00684258,
         -0.01241169, -0.04524273,  0.02328255,  0.01999135,
         -0.01833928,  0.02786035],
        [-0.00040803,  0.02106554, -0.0353395 ,  0.00684258,
         -0.01241169, -0.04524273,  0.02328255,  0.01999135,
         -0.01833928,  0.02786035],
        [-0.00040803,  0.02106554, -0.0353395 ,  0.00684258,
         -0.01241169, -0.04524273,  0.02328255,  0.01999135,
         -0.01833928,  0.02786035],
        [-0.01746012,  0.01134825,  0.01832283, -0.03126504,
          0.04912377,  0.01322078,  0.03017325,  0.04805828,
          0.04697359, -0.0299976 ],
        [ 0.02120974,  0.03046997, -0.00113782, -0.04402243,
          0.01540941,  0.01213721, -0.01075236, -0.00664486,
          0.0064547 ,  0.01457239],
        [ 0.02469445, -0.02066908, -0.00868576,  0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,  348, 5458, 1422, 1303])

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 198ms/step


array([[-0.00040803,  0.02106554, -0.0353395 ,  0.00684258, -0.01241169,
        -0.04524273,  0.02328255,  0.01999135, -0.01833928,  0.02786035],
       [-0.00040803,  0.02106554, -0.0353395 ,  0.00684258, -0.01241169,
        -0.04524273,  0.02328255,  0.01999135, -0.01833928,  0.02786035],
       [-0.00040803,  0.02106554, -0.0353395 ,  0.00684258, -0.01241169,
        -0.04524273,  0.02328255,  0.01999135, -0.01833928,  0.02786035],
       [-0.00040803,  0.02106554, -0.0353395 ,  0.00684258, -0.01241169,
        -0.04524273,  0.02328255,  0.01999135, -0.01833928,  0.02786035],
       [-0.01746012,  0.01134825,  0.01832283, -0.03126504,  0.04912377,
         0.01322078,  0.03017325,  0.04805828,  0.04697359, -0.0299976 ],
       [ 0.02120974,  0.03046997, -0.00113782, -0.04402243,  0.01540941,
         0.01213721, -0.01075236, -0.00664486,  0.0064547 ,  0.01457239],
       [ 0.02469445, -0.02066908, -0.00868576,  0.04119375,  0.02803625,
         0.01470738,  0.0114833 ,  0.01022283